name: Create gh-pages branch
on:
  push:
    branches:
      - main
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create gh-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git ls-remote --exit-code --heads origin gh-pages
          if [ $? -ne 0 ]; then
            echo "gh-pages branch does not exist. Creating it now."
            git checkout --orphan gh-pages
            git rm -rf .
            git commit --allow-empty -m "Initial commit"
            git push origin gh-pages
          else
            echo "gh-pages branch already exists."
          fi
